### ISSUE TITLE
3MB leak in ASDepthModal / ASDepthModal / UIImage+Blur.m

### ISSUE THREAD

**Issue by cichun** [autresphere/ASDepthModal#22]
There is a leak in -(UIImage *)boxblurImageWithBlur:(CGFloat)blur.
The pixelBuffer2 is never released. Each time you call presentView: from ASDepthModalViewController the sample application consumes 3MB of memory.
I know this function is borrowed from https://github.com/rnystrom/RNBlurModalView/blob/master/RNBlurModalView.m but in the original code there is additional line(#700) in the cleanup section "free(pixelBuffer2)" - this will fix the issue.

Memory consumption at the begining:
![start](https://cloud.githubusercontent.com/assets/7638234/3023271/6a5d349e-dfe1-11e3-8b72-54d95db15d1f.png)

Memory consumption after firing ASDepthModal several times:
![leak](https://cloud.githubusercontent.com/assets/7638234/3023281/9c84a312-dfe1-11e3-9be4-951d32790266.png)

**Comment by autresphere** [comment]
Thanks a lot for the fix!
